name: Sync Fork

on:
  schedule:
    - cron: '0 3 * * *' # 每天凌晨3点
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Sync with upstream
        run: |
          git config --global user.name 'Your Name'
          git config --global user.email 'you@example.com'
          git remote add upstream https://github.com/PublicAffairs/openai-gemini.git
          git fetch upstream
          git checkout main
          git merge upstream/main
          git push origin main
